INSERT INTO media VALUES ("ltr_rog626","letter","1861-11-17","Washington","DC","US","Rose","Greenhow",NULL,"William","Seward",NULL,"individual",NULL,"For nearly three months I have been confined, a close prisoner, shut out from air and exercise...","ltr_rog626.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,1);
INSERT INTO media VALUES ("ltr_rog627","letter","1863-06-19","Richmond","VA","US","Rose","Greenhow",NULL,"Alexander","Boteler",NULL,"individual",NULL,"I saw the President this morning and he affords me every facility and and in carrying out my mischief","ltr_rog627.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,0);
INSERT INTO media VALUES ("ltr_rog628","letter","1863-07-16","Charleston","SC","US","Rose","Greenhow",NULL,"Jefferson","Davis",NULL,"individual",NULL,"On reaching Wilmington the situation of Charleston became the engrossing subject of conversation and of interest","ltr_rog628.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,0);
INSERT INTO media VALUES ("ltr_rog629","letter","1863-07-20","Charleston","SC","US","Rose","Greenhow",NULL,"Alexander","Boteler",NULL,"individual",NULL,"the skill and daring of our people will be taxed to the utmost to repell the brutal hoards who are now hovering around.","ltr_rog629.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,0);
INSERT INTO media VALUES ("ltr_rog630","letter","1863-07-23","Charleston","SC","US","Rose","Greenhow",NULL,"Alexander","Boteler",NULL,"individual",NULL,"finding it impossible to get out from this port I have remained here","ltr_rog630.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,0);
INSERT INTO media VALUES ("ltr_rog631","letter","1863-08-13","St George","Bermu","ENG","Rose","Greenhow",NULL,"Alexander","Boteler",NULL,"individual",NULL,"I have as you will see arrived here in despite of Yankee crusiers who gave us a close chase all the way","ltr_rog631.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,0);
INSERT INTO media VALUES ("ltr_rog632","letter","1863-12-10","London","","ENG","Rose","Greenhow",NULL,"Alexander","Boteler",NULL,"individual",NULL,"I trust that my friends will not forget me or believe that even amidst the enjoyments of my present existance that I can for a moment be oblivious of the friends I have left behind","ltr_rog632.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,0);
INSERT INTO media VALUES ("ltr_rog633","letter","1864-02-17","London","","ENG","Rose","Greenhow",NULL,"Alexander","Boteler",NULL,"individual",NULL,"I had the honor of an audience with the Emperor...","ltr_rog633.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,109,0);
INSERT INTO media VALUES ("ltr_rog6000","letter","1849-08-29","Washington","MD","US","Rose","Greenhow","","John","Calhoun","","individual","","Now I must tell you of the progress of the Cuba affair. The main spring or mover in the matter has just left me","ltr_rog6000.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,61,0);
