INSERT INTO media VALUES ("ltr_ccp3900","letter","1776-06-05","Fort Johnston","SC","US","Charles","Pinckney","Jr","Eliza","Lucas","","individual","","Lest my honored mother should be alarmed by hearing exaggerated reports of the fleet off the bar, I snatch a few minutes from the duties of my station to acquaint her of the particulars of it.","ltr_ccp3900.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,104,0);
INSERT INTO media VALUES ("ltr_ccp3901","letter","1776-06-15","Fort Johnston","SC","US","Charles","Pinckney","Jr","Eliza","Lucas","","individual","","No attack has been made upon us yet, and from the strange conduct of the gentry in Five-Fathom Hole, I don t know when to expect one.","ltr_ccp3901.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,104,0);
INSERT INTO media VALUES ("ltr_ccp3902","letter","1776-06-17","Fort Johnston","SC","US","Charles","Pinckney","Jr","Eliza","Lucas","","individual","","The enemy has not thought fit to make any attack upon us yet. They employed themselves yesterday in landing some men on LongIsland (a small creek parts it from Sullivan's Island)","ltr_ccp3902.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,104,0);
INSERT INTO media VALUES ("ltr_ccp3903","letter","1776-06-29","Fort Johnston","SC","US","Charles","Pinckney","Jr","Eliza","Lucas","","individual","","I am sure my honored Mother must be anxious to know the event of yesterday's cannonade. I therefore take the earliest opportunity of acquainting her with the particulars of it.","ltr_ccp3903.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,104,0);
INSERT INTO media VALUES ("ltr_ccp3904","letter","1782-05-19","Pon Pon","SC","US","Charles","Pinckney","Jr","John","Matthews","","individual","","a Col. Perkins, a trader from Virginia, has contracted for five or six hundred head of cattle on Pee Dee and the Cheraws, and which in a few days will be drove off for Virginia","ltr_ccp3904.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,104,0);
INSERT INTO media VALUES ("ltr_ccp3905","letter","1779-02-24","Charleston","SC","US","Charles","Pinckney","Jr","Eliza","Lucas","","individual","","I embrace with pleasure an opportunity of complying with the request, you made me when I left Santee, of transmitting such intelligence as I thought worthy your notice","ltr_ccp3905.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,104,0);
INSERT INTO media VALUES ("ltr_ccp3906","letter","1779-03-28","Charleston","SC","US","Charles","Pinckney","Jr","Eliza","Lucas","","individual","","Since that General Lincoln has thought proper to re move the army from Purysburgh to the two Sisters (except about three hundred left as a guard to their camp under the command of Col. Pinckney) where it seems the enemy have assembled their whole for","ltr_ccp3906.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,104,0);
INSERT INTO media VALUES ("ltr_ccp4300","letter","1788-05-24","Charleston","SC","US","Charles","Pinckney","","George","Washington","","individual","","South Carolina has ratified the Federal Constitution. Our Convention assembled the 12th instant, and yesterday the vote of ratification was taken","ltr_ccp4300.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,60,0);
INSERT INTO media VALUES ("ltr_ccp4301","letter","1790-06-19","Charleston","SC","US","Charles","Pinckney","","George","Washington","","individual","","I am infinitely obliged to you, for having favored me with introductory letters for my nephew, Mr. Horry. It will give him an opportunity of travelling with such great advantage","ltr_ccp4301.txt","hans.brough@yahoo.com",NULL,20090802183836,NULL,60,0);
