INSERT INTO media VALUES ('ltr_geg6950','letter','1777-03-03','Whitehall','','ENG','George','Germain','','William','Howe','','individual','','the King very much applauds the ability and conduct which his Lordship displayed in the close pursuit of the enemy from Fort Lee to Trenton','ltr_geg6950.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',1);
INSERT INTO media VALUES ('ltr_geg6951','letter','1778-04-12','Whitehall','','ENG','George','Germain','','Charles','Cornwallis','','individual','','you should have a dormant commission giving you the rank of General in America only','ltr_geg6951.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',0);
INSERT INTO media VALUES ('ltr_geg6952','letter','1778-08-06','Pall Mall','','ENG','George','Germain','','Charles','Cornwallis','','individual','','at present he cannot dispense with your service in North America, especially as your lordship has a dormant commission to command all the forces there','ltr_geg6952.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',0);
INSERT INTO media VALUES ('ltr_geg6953','letter','1779-04-11','Whitehall','','ENG','George','Germain','','Henry','Clinton','','individual','','Lord Cornwallis went to Court, and made an offer of his services to the King which you will not doubt his Majesty was graciously pleased to accept','ltr_geg6953.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',0);
INSERT INTO media VALUES ('ltr_geg6954','letter','1779-11-04',' Whitehall','','US','George','Germain','','Henry','Clinton','','individual','','Though the King has great confidence in his Lordship\'s abilities, yet his Majesty is too well satisfied with your conduct to wish to see the command of his forces in any other hands','ltr_geg6954.txt','hans.brough@yahoo.com',NULL,20090823142222,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',1);
INSERT INTO media VALUES ('ltr_geg6955','letter','1780-11-09','Whitehall','','ENG','George','Germain','','Charles','Cornwallis','','individual','','which I immediately laid before the King, who read with the highest satisfaction the account of the very glorious and complete victory obtained by your Lordship over the Rebels near Camden','ltr_geg6955.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',0);
INSERT INTO media VALUES ('ltr_geg6956','letter','1781-03-07','Whitehall','','ENG','George','Germain','','Charles','Cornwallis','','individual','','The reasons which you assign for calling General Leslie from Virginia are founded in wisdom, and could not fail being approved by the King','ltr_geg6956.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',0);
INSERT INTO media VALUES ('ltr_geg6957','letter','1781-06-04','Whitehall','','ENG','George','Germain','','Charles','Cornwallis','','individual','','His Majesty\'s ship Galatea, which arrived on the 19th of last month, brought me a letter from Lord Rawdon, enclosing a note from your Lordship to him','ltr_geg6957.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',0);
INSERT INTO media VALUES ('ltr_geg6958','letter','1781-06-06','Whitehall','','ENG','George','Germain','','Henry','Clinton','','individual','','the great importance of pushing the war on the side of Virginia with all the force that can be spared, until that province is reduced.','ltr_geg6958.txt','hans.brough@yahoo.com',NULL,20090802183836,NULL,'Correspondence of Charles, first Marquis Cornwallis, Vol I, Charles Ross, Esq., London, 1859',0);
